(in-package #:antaios)

;;;; -- Fullscreen Behavior --

(-> fullscreen-test--ui (terminal) terminal-ui)
(defun fullscreen-test--ui (terminal)
  "Construct a fullscreen UI around a deterministic terminal."
  (terminal-ui-create :terminal terminal :fullscreen-p t :prompt "> "))

(-> test-terminal-fullscreen-viewport () null)
(defun test-terminal-fullscreen-viewport ()
  "Exercise pinned geometry, scrolling, streaming, deduplication and width reflow."
  (let ((terminal (make-instance 'recording-terminal :columns 32 :rows 12)))
    (with-terminal-ui (ui (fullscreen-test--ui terminal))
      (terminal-ui-set-input ui "draft")
      (terminal-ui-append-finalized-batch
       ui (loop for index below 30 collect (list index (format nil "row ~D: alpha beta gamma delta" index))))
      (multiple-value-bind (frame row column) (terminal-ui-fullscreen--frame ui nil)
        (test-assert (= (length frame) 12) "frame fills the complete height")
        (test-assert (= row 10) "composer is pinned above its bottom spacer")
        (test-assert (= column 7) "composer cursor uses the prompt and draft")
        (test-assert (search "draft" (clinedi:ansi-strip (nth row frame))) "draft is visible"))
      (terminal-ui-process-event ui ':page-up)
      (let* ((top (fullscreen-terminal-ui-top ui))
             (anchor (aref (fullscreen-terminal-ui-rows ui) top)))
        (test-assert (integerp top) "page-up leaves tail-follow mode")
        (terminal-ui-append-finalized ui ':later "new output")
        (terminal-ui-stream-update ui :tail "still streaming")
        (test-assert (= top (fullscreen-terminal-ui-top ui)) "streaming preserves the scrolled position")
        (terminal-ui-resize ui 17 :rows 12)
        (let ((reflowed (aref (fullscreen-terminal-ui-rows ui) (fullscreen-terminal-ui-top ui))))
          (test-assert (= (fullscreen-row-chunk anchor) (fullscreen-row-chunk reflowed))
                       "resize keeps the visible source chunk")
          (test-assert (<= (fullscreen-row-offset reflowed) (fullscreen-row-offset anchor))
                       "resize retains the source position within its reflowed row")))
      (let ((rows (fullscreen-terminal-ui-rows ui))
            (count (length (fullscreen-terminal-ui-chunks ui))))
        (terminal-ui--paint-live ui)
        (test-assert (eq rows (fullscreen-terminal-ui-rows ui)) "redraw reuses the indexed cache")
        (test-assert (not (terminal-ui-append-finalized ui ':later "duplicate")) "finalized ids deduplicate")
        (test-assert (= count (length (fullscreen-terminal-ui-chunks ui))) "deduplication does not extend history"))
      (terminal-ui-process-event ui ':scroll-bottom)
      (test-assert (null (fullscreen-terminal-ui-top ui)) "Ctrl-End follows the tail")
      (terminal-ui-process-event ui '(:scroll -1))
      (test-assert (integerp (fullscreen-terminal-ui-top ui)) "wheel-up scrolls history")
      (test-assert (string= "draft" (line-editor-text (terminal-ui-editor ui))) "scrolling preserves the draft")))
  nil)

(-> test-terminal-fullscreen-small-windows () null)
(defun test-terminal-fullscreen-small-windows ()
  "Keep Unicode drafts and the cursor inside resized, even one-cell, viewports."
  (let ((terminal (make-instance 'recording-terminal :columns 40 :rows 12)))
    (with-terminal-ui (ui (fullscreen-test--ui terminal))
      (terminal-ui-set-input ui (format nil "猫 e~C abcdefghijklmnopqrstuvwxyz~%last" (code-char #x301)))
      (dolist (width '(1 2 7 12 40))
        (dolist (height '(1 2 3 8 24))
          (terminal-ui-resize ui width :rows height)
          (multiple-value-bind (frame row column) (terminal-ui-fullscreen--frame ui nil)
            (test-assert (= (length frame) height) "every frame covers its viewport")
            (test-assert (and (<= 0 row) (< row height)) "cursor row fits")
            (test-assert (and (<= 0 column) (< column width)) "cursor column fits")
            (test-assert (every (lambda (display) (<= (clinedi:ansi-display-width display) width)) frame)
                         "wide and combining glyphs do not overrun a row"))))))
  nil)

(-> test-terminal-fullscreen-failure-and-lifecycle () null)
(defun test-terminal-fullscreen-failure-and-lifecycle ()
  "Roll back failed transcript paints and release an owned alternate screen exactly once."
  (let* ((terminal (make-instance 'failing-recording-terminal :columns 40 :rows 12))
         (ui (fullscreen-test--ui terminal)))
    (unwind-protect
         (progn
           (terminal-ui-start ui)
           (terminal-ui-start ui)
           (setf (failing-recording-terminal-fail-next-write-p terminal) t)
           (test-assert
            (handler-case (progn (terminal-ui-append-finalized ui ':retry "hello") nil)
              (terminal-error () t)) "paint failure is propagated")
           (test-assert (zerop (length (fullscreen-terminal-ui-chunks ui))) "failed append restores history")
           (test-assert (terminal-ui-append-finalized ui ':retry "hello") "failed append can be retried")
           (test-assert (= 1 (length (fullscreen-terminal-ui-chunks ui))) "retry commits once"))
      (terminal-ui-stop ui))
    (let ((count (length (recording-terminal-chunks terminal))))
      (terminal-ui-stop ui)
      (test-assert (= count (length (recording-terminal-chunks terminal))) "repeated stop emits no control bytes"))
    (test-assert (not (fullscreen-terminal-ui-active-p ui)) "alternate ownership released"))
  (let* ((destination (make-string-output-stream))
         (stream (make-instance 'fullscreen-output-stream :output destination))
         (enter (format nil "~C[?1049h" #\Escape))
         (leave (format nil "~C[?1049l" #\Escape)))
    (fullscreen-output-stream-restore stream)
    (test-assert (string= "" (get-output-stream-string destination)) "inline client cleanup emits no controls")
    (loop for character across enter do (write-char character stream))
    (test-assert (fullscreen-output-stream-active-p stream) "split packets acquire ownership")
    (get-output-stream-string destination)
    (fullscreen-output-stream-restore stream)
    (test-assert (search leave (get-output-stream-string destination)) "connection loss restores owned screen")
    (fullscreen-output-stream-restore stream)
    (test-assert (string= "" (get-output-stream-string destination)) "client cleanup is idempotent")
    (write-string (concatenate 'string enter "frame" leave) stream)
    (test-assert (not (fullscreen-output-stream-active-p stream)) "remote leave releases ownership")
    (let ((set-background (format nil "~C]11;rgb:19/3C/B8~C" #\Escape #\Bel))
          (resets (concatenate 'string
                               (default-color-reset-sequence ':foreground)
                               (default-color-reset-sequence ':background))))
      (get-output-stream-string destination)
      (write-string (subseq set-background 0 4) stream)
      (write-string (subseq set-background 4) stream)
      (test-assert (fullscreen-output-stream-theme-colors-p stream)
                   "a split default-color command is recognized")
      (get-output-stream-string destination)
      (fullscreen-output-stream-restore stream)
      (test-assert (search resets (get-output-stream-string destination))
                   "connection loss restores imposed default colors")
      (write-string (concatenate 'string set-background resets) stream)
      (test-assert (not (fullscreen-output-stream-theme-colors-p stream))
                   "remote resets release the default colors")
      (write-string (format nil "~C]133;A~C~C]8;;~C\\" #\Escape #\Bel #\Escape #\Escape) stream)
      (get-output-stream-string destination)
      (fullscreen-output-stream-restore stream)
      (test-assert (string= "" (get-output-stream-string destination))
                   "other operating-system commands never trigger a color reset")))
  (let* ((terminal (make-instance 'recording-terminal :columns 30 :rows 10))
         (ui (fullscreen-test--ui terminal)))
    (with-terminal-ui (active ui)
      (terminal-ui-append-finalized active ':before "before detach")
      (setf (terminal-interactive-p terminal) nil)
      (terminal-ui-detach active)
      (terminal-ui-append-finalized active ':detached "while detached")
      (test-assert (not (fullscreen-terminal-ui-active-p active)) "detached output does not reenter")
      (setf (terminal-interactive-p terminal) t)
      (terminal-ui-resize active 40 :rows 12)
      (test-assert (fullscreen-terminal-ui-active-p active) "attachment resize reenters fullscreen")
      (test-assert (= 2 (length (fullscreen-terminal-ui-chunks active))) "reattach retains transcript")))
  nil)


(-> test-terminal-fullscreen-relayed-wheel () null)
(defun test-terminal-fullscreen-relayed-wheel ()
  "Decode framed remote wheel packets and scroll the viewport across reattachment."
  (let* ((terminal (localgroup-terminal-create))
         (packets (with-output-to-string (stream)
                    (dolist (event '((:scroll 0) (:scroll "up") (:scroll -1 :extra)
                                     (:scroll -1) (:scroll 1)))
                      (daemon-write-packet stream (list :event event)))))
         (output (make-string-output-stream))
         (attachment (make-instance 'image-daemon:attachment :socket nil :mode ':control
                                    :stream (make-two-way-stream (make-string-input-stream packets) output)))
         (ui (fullscreen-test--ui terminal)))
    (image-daemon:relay-attach terminal attachment :rows 12 :columns 40 :styled-p nil :session-id "wheel-test")
    (unwind-protect
         (with-terminal-ui (active ui)
           (terminal-ui-set-input active "draft")
           (terminal-ui-append-finalized-batch
            active (loop for index below 30 collect (list index (format nil "row ~D" index))))
           (image-daemon:relay-read-attachment terminal attachment :event-validator #'localgroup--terminal-event-p)
           (test-assert (terminal-input-ready-p terminal) "valid wheel packets reach the relay queue")
           (terminal-ui-process-event active (terminal-read-event terminal))
           (test-assert (= (- (fullscreen-terminal-ui-maximum-top active) 3)
                           (fullscreen-terminal-ui-top active)) "remote wheel-up scrolls three rows")
           (terminal-ui-process-event active (terminal-read-event terminal))
           (test-assert (null (fullscreen-terminal-ui-top active)) "remote wheel-down returns to the tail")
           (test-assert (not (terminal-input-ready-p terminal)) "malformed wheel packets were rejected")
           (test-assert (string= "draft" (line-editor-text (terminal-ui-editor active))) "wheel input preserves the draft"))
      (image-daemon:relay-detach terminal attachment)
      (terminal-ui-stop ui)))
  (let ((terminal (make-instance 'recording-terminal :columns 40 :rows 12)))
    (with-terminal-ui (ui (fullscreen-test--ui terminal))
      (terminal-ui-fullscreen-leave ui)
      (setf (recording-terminal-chunks terminal) nil)
      (terminal-ui-open-prompt-block ui)
      (test-assert (fullscreen-terminal-ui-active-p ui) "reopening a detached prompt acquires fullscreen")
      (test-assert (some (lambda (chunk) (search (format nil "~C[?1006h" #\Escape) chunk))
                         (recording-terminal-chunks terminal))
                   "prompt reopening restores mouse reporting")))
  nil)


;;;; -- Transcript Clicks --

(-> test-terminal-fullscreen-clicks () null)
(defun test-terminal-fullscreen-clicks ()
  "Test clicks resolve to copy widgets and web URLs across streaming, scrolling, and deferral."
  (let ((terminal (make-instance 'recording-terminal :columns 40 :rows 12))
        (actions nil))
    (with-terminal-ui (ui (fullscreen-test--ui terminal))
      (setf (terminal-ui-action-function ui)
            (lambda (action)
              (push action actions)))
      (terminal-ui-append-finalized
       ui ':first
       (list (terminal-span ':plain "see https://example.com/doc now")
             (terminal-span ':plain (string #\Newline))
             (terminal-span ':dim "  ``` ")
             (termdown:make-widget ':code-copy "⧉ copy" '(:copy "(+ 1 2)"))))
      (terminal-ui-process-event ui '(:click 10 1))
      (test-assert (equal '(:open-url "https://example.com/doc") (first actions))
                   "clicking a URL opens it")
      (terminal-ui-process-event ui '(:click 2 1))
      (test-assert (= 1 (length actions)) "clicking plain text does nothing")
      (terminal-ui-process-event ui '(:click 9 2))
      (test-assert (equal '(:copy "(+ 1 2)") (first actions))
                   "clicking the copy label copies the fence source")
      (terminal-ui-process-event ui '(:click 30 2))
      (test-assert (= 2 (length actions)) "clicking past the row end does nothing")
      (terminal-ui-stream-update
       ui
       :rows (list (list (terminal-span ':plain "streamed ")
                         (termdown:make-widget ':code-copy "⧉ copy" '(:copy "streamed source"))))
       :tail nil)
      (terminal-ui-process-event ui '(:click 12 4))
      (test-assert (equal '(:copy "streamed source") (first actions))
                   "streamed rows keep their click regions")
      (terminal-ui-append-finalized-batch
       ui (loop for index below 30
                collect (list index (format nil "row https://example.com/~D" index))))
      (terminal-ui-process-event ui ':scroll-top)
      (terminal-ui-process-event ui '(:click 10 1))
      (test-assert (equal '(:open-url "https://example.com/doc") (first actions))
                   "clicks after scrolling resolve through the visible top row")
      (terminal-ui-process-event ui ':scroll-bottom)
      (terminal-ui-process-event ui '(:click 10 2))
      (test-assert (equal '(:open-url "https://example.com/26") (first actions))
                   "clicks while following the tail resolve through the painted window")
      (terminal-ui-resize ui 20 :rows 12)
      (terminal-ui-process-event ui ':scroll-top)
      (terminal-ui-process-event ui '(:click 5 2))
      (test-assert (equal '(:open-url "https://example.com/doc") (first actions))
                   "reflowed rows still resolve the whole URL from their chunk")
      (setf (terminal-ui-live-output-suspended-p ui) t)
      (terminal-ui-append-finalized
       ui ':deferred
       (list (termdown:make-widget ':code-copy "⧉ copy" '(:copy "deferred"))))
      (setf (terminal-ui-live-output-suspended-p ui) nil)
      (terminal-ui--paint-live ui)
      (terminal-ui-process-event ui ':scroll-bottom)
      (terminal-ui-process-event ui '(:click 1 8))
      (test-assert (equal '(:copy "deferred") (first actions))
                   "regions deferred during direct terminal I/O survive the resume")
      (setf (terminal-ui-action-function ui) nil)
      (terminal-ui-process-event ui '(:click 1 8))
      (test-assert (= 7 (length actions))
                   "clicks without an installed action function are ignored")))
  nil)

(-> test-localgroup-click-events () null)
(defun test-localgroup-click-events ()
  "Test relayed click packets are accepted only with bounded one-based coordinates."
  (dolist (case '(((:click 3 7) t)
                  ((:click 1 1) t)
                  ((:click 0 7) nil)
                  ((:click 3 0) nil)
                  ((:click 3 7 1) nil)
                  ((:click "3" 7) nil)
                  ((:click 3 10001) nil)
                  ((:scroll -1) t)))
    (destructuring-bind (event expected) case
      (test-assert (eq expected (localgroup--terminal-event-p event))
                   (format nil "relay validation of ~S" event))))
  nil)


;;;; -- Message Jumps and Exit Epilogue --

(-> fullscreen-test--row-text (fullscreen-terminal-ui integer) string)
(defun fullscreen-test--row-text (ui index)
  "Return the plain text of UI's committed transcript row INDEX."
  (let* ((row (aref (fullscreen-terminal-ui-rows ui) index))
         (text (first (aref (fullscreen-terminal-ui-chunks ui) (fullscreen-row-chunk row))))
         (start (fullscreen-row-offset row)))
    (subseq text start (+ start (fullscreen-row-length row)))))

(-> test-terminal-fullscreen-message-jumps () null)
(defun test-terminal-fullscreen-message-jumps ()
  "Test Ctrl-Page jumps land on user and assistant headers while skipping activity rows."
  (let* ((terminal (make-instance 'recording-terminal :columns 40 :rows 12))
         (ui (terminal-ui-create :terminal terminal :fullscreen-p t :prompt "> "
                                 :message-header-prefixes '("❯ you" "● antaios"))))
    (with-terminal-ui (active ui)
      (terminal-ui-append-finalized-batch
       active
       (loop for turn below 4
             append (list (list (list :user turn)
                                (format nil "❯ you 12:0~D~%question ~D" turn turn))
                          (list (list :tool turn)
                                (format nil "▸ tool ~D~%│ output line~%│ more output" turn))
                          (list (list :agent turn)
                                (format nil "● antaios~%answer ~D continues here" turn)))))
      (terminal-ui-process-event active ':scroll-bottom)
      (terminal-ui-process-event active ':previous-section)
      (let ((top (fullscreen-terminal-ui-top active)))
        (test-assert (and top (uiop:string-prefix-p "❯ you 12:03" (fullscreen-test--row-text active top)))
                     "Ctrl-PgUp from the tail tops the newest header above the window"))
      (terminal-ui-process-event active ':previous-section)
      (let ((top (fullscreen-terminal-ui-top active)))
        (test-assert (and top (uiop:string-prefix-p "● antaios" (fullscreen-test--row-text active top)))
                     "a second Ctrl-PgUp skips tool rows and tops the previous assistant header"))
      (terminal-ui-process-event active ':next-section)
      (let ((top (fullscreen-terminal-ui-top active)))
        (test-assert (and top (uiop:string-prefix-p "❯ you 12:03" (fullscreen-test--row-text active top)))
                     "Ctrl-PgDn returns to the following user header"))
      (terminal-ui-process-event active ':next-section)
      (test-assert (null (fullscreen-terminal-ui-top active))
                   "jumping past the final window follows the tail again")
      (terminal-ui-process-event active ':scroll-top)
      (terminal-ui-process-event active ':previous-section)
      (test-assert (eql 0 (fullscreen-terminal-ui-top active))
                   "Ctrl-PgUp at the first row stays put")
      (terminal-ui-process-event active ':next-section)
      (let ((top (fullscreen-terminal-ui-top active)))
        (test-assert (and top (uiop:string-prefix-p "● antaios" (fullscreen-test--row-text active top)))
                     "Ctrl-PgDn from the first user header reaches the first assistant header"))
      (test-assert (string= "draft" (progn (terminal-ui-set-input active "draft")
                                           (line-editor-text (terminal-ui-editor active))))
                   "message jumps leave the draft alone")))
  nil)

(-> test-terminal-fullscreen-exit-epilogue () null)
(defun test-terminal-fullscreen-exit-epilogue ()
  "Test epilogue text reaches the normal screen after the alternate buffer is left."
  (let* ((terminal (make-instance 'recording-terminal :columns 40 :rows 12))
         (ui (fullscreen-test--ui terminal)))
    (terminal-ui-start ui)
    (terminal-ui-append-finalized ui ':first "transcript row")
    (terminal-ui-set-epilogue ui (list (terminal-span ':dim "To resume this conversation, run:")
                                       (terminal-span ':plain (string #\Newline))
                                       (terminal-span ':code "  antaios resume abc")))
    (recording-terminal-reset terminal)
    (terminal-ui-stop ui)
    (let* ((output (recording-terminal-output terminal))
           (leave (search (format nil "~C[?1049l" #\Escape) output))
           (advice (search "antaios resume abc" output)))
      (test-assert (and leave advice (< leave advice))
                   "the epilogue is written after the alternate buffer is restored")))
  nil)
