(require :asdf)

(let* ((script-path (truename *load-truename*))
       (server-root (uiop:pathname-directory-pathname script-path))
       (source-root (uiop:pathname-parent-directory-pathname server-root))
       (project-setup (merge-pathnames ".qlot/setup.lisp" source-root)))
  (unless (probe-file project-setup)
    (error "The release server needs locked dependencies; run ./script/bootstrap."))
  (load project-setup)
  (asdf:load-asd (merge-pathnames "antaios.asd" source-root))
  (asdf:load-system :antaios/release-server)
  (uiop:symbol-call '#:antaios '#:release-server-main))
