#!/bin/sh

exec 2>&1

export HOME=/var/lib/antaios-release-server/home
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache
export ANTAIOS_RELEASE_SOURCE_ROOT=/srv/antaios-release-server/current
export ANTAIOS_RELEASE_PUBLIC_ROOT=/srv/antaios-release-server/public
export ANTAIOS_RELEASE_LISTEN_ADDRESS=127.0.0.1
export ANTAIOS_RELEASE_LISTEN_PORT=8098

exec s6-setuidgid antaios-release \
  /srv/antaios-release-server/current/server/run serve
