#!/bin/sh

exec 2>&1

umask 022

export HOME=/var/lib/antaios-release-server/home
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=/var/lib/antaios-release-server/updater/state
export XDG_CACHE_HOME=/var/lib/antaios-release-server/updater/cache
export ANTAIOS_RELEASE_SOURCE_ROOT=/srv/antaios-release-server/current
export ANTAIOS_RELEASE_SELECTION_PATH=/srv/antaios-release-server/current
export ANTAIOS_RELEASE_DEPLOYMENTS_ROOT=/srv/antaios-release-server/deployments
export ANTAIOS_RELEASE_UPDATER_STATE_ROOT=/var/lib/antaios-release-server/updater
export ANTAIOS_RELEASE_PUBLIC_ROOT=/srv/antaios-release-server/public
export ANTAIOS_RELEASE_STATE_ROOT=/var/lib/antaios-release-server/builder
export ANTAIOS_RELEASE_UPDATE_POLL_SECONDS=60
export ANTAIOS_RELEASE_SERVICE_HOME=/var/lib/antaios-release-server/home

if [ -f /srv/antaios-release-server/current/server/release-updater.lisp ]; then
  exec /srv/antaios-release-server/current/server/run update
fi

exec /srv/antaios-release-server/source/server/run update
